<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Country>
 */
class CountryFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $countries = [
            ['name' => 'United States', 'code' => 'US'],
            ['name' => 'Canada', 'code' => 'CA'],
            ['name' => 'United Kingdom', 'code' => 'GB'],
            ['name' => 'Germany', 'code' => 'DE'],
            ['name' => 'France', 'code' => 'FR'],
            ['name' => 'Italy', 'code' => 'IT'],
            ['name' => 'Spain', 'code' => 'ES'],
            ['name' => 'Netherlands', 'code' => 'NL'],
            ['name' => 'Belgium', 'code' => 'BE'],
            ['name' => 'Switzerland', 'code' => 'CH'],
            ['name' => 'Austria', 'code' => 'AT'],
            ['name' => 'Sweden', 'code' => 'SE'],
            ['name' => 'Norway', 'code' => 'NO'],
            ['name' => 'Denmark', 'code' => 'DK'],
            ['name' => 'Finland', 'code' => 'FI'],
            ['name' => 'Poland', 'code' => 'PL'],
            ['name' => 'Czech Republic', 'code' => 'CZ'],
            ['name' => 'Hungary', 'code' => 'HU'],
            ['name' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Greece', 'code' => 'GR'],
            ['name' => 'Ireland', 'code' => 'IE'],
            ['name' => 'Australia', 'code' => 'AU'],
            ['name' => 'New Zealand', 'code' => 'NZ'],
            ['name' => 'Japan', 'code' => 'JP'],
            ['name' => 'South Korea', 'code' => 'KR'],
            ['name' => 'Singapore', 'code' => 'SG'],
            ['name' => 'Hong Kong', 'code' => 'HK'],
            ['name' => 'India', 'code' => 'IN'],
            ['name' => 'China', 'code' => 'CN'],
            ['name' => 'Brazil', 'code' => 'BR'],
            ['name' => 'Argentina', 'code' => 'AR'],
            ['name' => 'Mexico', 'code' => 'MX'],
            ['name' => 'Chile', 'code' => 'CL'],
            ['name' => 'Colombia', 'code' => 'CO'],
            ['name' => 'Peru', 'code' => 'PE'],
            ['name' => 'South Africa', 'code' => 'ZA'],
            ['name' => 'Egypt', 'code' => 'EG'],
            ['name' => 'Nigeria', 'code' => 'NG'],
            ['name' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Morocco', 'code' => 'MA'],
            ['name' => 'Israel', 'code' => 'IL'],
            ['name' => 'Turkey', 'code' => 'TR'],
            ['name' => 'Russia', 'code' => 'RU'],
            ['name' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'Thailand', 'code' => 'TH'],
            ['name' => 'Malaysia', 'code' => 'MY'],
            ['name' => 'Indonesia', 'code' => 'ID'],
            ['name' => 'Philippines', 'code' => 'PH'],
            ['name' => 'Vietnam', 'code' => 'VN'],
            ['name' => 'Taiwan', 'code' => 'TW'],
            ['name' => 'United Arab Emirates', 'code' => 'AE'],
            ['name' => 'Saudi Arabia', 'code' => 'SA'],
            ['name' => 'Qatar', 'code' => 'QA'],
            ['name' => 'Kuwait', 'code' => 'KW'],
            ['name' => 'Bahrain', 'code' => 'BH'],
            ['name' => 'Oman', 'code' => 'OM'],
            ['name' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Lebanon', 'code' => 'LB'],
            ['name' => 'Cyprus', 'code' => 'CY'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Iceland', 'code' => 'IS'],
            ['name' => 'Luxembourg', 'code' => 'LU'],
            ['name' => 'Estonia', 'code' => 'EE'],
            ['name' => 'Latvia', 'code' => 'LV'],
            ['name' => 'Lithuania', 'code' => 'LT'],
            ['name' => 'Slovenia', 'code' => 'SI'],
            ['name' => 'Slovakia', 'code' => 'SK'],
            ['name' => 'Croatia', 'code' => 'HR'],
            ['name' => 'Romania', 'code' => 'RO'],
            ['name' => 'Bulgaria', 'code' => 'BG'],
            ['name' => 'Serbia', 'code' => 'RS'],
            ['name' => 'Montenegro', 'code' => 'ME'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['name' => 'North Macedonia', 'code' => 'MK'],
            ['name' => 'Albania', 'code' => 'AL'],
            ['name' => 'Moldova', 'code' => 'MD'],
            ['name' => 'Belarus', 'code' => 'BY'],
            ['name' => 'Georgia', 'code' => 'GE'],
            ['name' => 'Armenia', 'code' => 'AM'],
            ['name' => 'Azerbaijan', 'code' => 'AZ'],
            ['name' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'Tajikistan', 'code' => 'TJ'],
            ['name' => 'Turkmenistan', 'code' => 'TM'],
            ['name' => 'Mongolia', 'code' => 'MN'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Bhutan', 'code' => 'BT'],
            ['name' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Maldives', 'code' => 'MV'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Iran', 'code' => 'IR'],
            ['name' => 'Iraq', 'code' => 'IQ'],
            ['name' => 'Syria', 'code' => 'SY'],
            ['name' => 'Yemen', 'code' => 'YE'],
            ['name' => 'Oman', 'code' => 'OM'],
            ['name' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Lebanon', 'code' => 'LB'],
            ['name' => 'Cyprus', 'code' => 'CY'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Iceland', 'code' => 'IS'],
            ['name' => 'Luxembourg', 'code' => 'LU'],
            ['name' => 'Estonia', 'code' => 'EE'],
            ['name' => 'Latvia', 'code' => 'LV'],
            ['name' => 'Lithuania', 'code' => 'LT'],
            ['name' => 'Slovenia', 'code' => 'SI'],
            ['name' => 'Slovakia', 'code' => 'SK'],
            ['name' => 'Croatia', 'code' => 'HR'],
            ['name' => 'Romania', 'code' => 'RO'],
            ['name' => 'Bulgaria', 'code' => 'BG'],
            ['name' => 'Serbia', 'code' => 'RS'],
            ['name' => 'Montenegro', 'code' => 'ME'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['name' => 'North Macedonia', 'code' => 'MK'],
            ['name' => 'Albania', 'code' => 'AL'],
            ['name' => 'Moldova', 'code' => 'MD'],
            ['name' => 'Belarus', 'code' => 'BY'],
            ['name' => 'Georgia', 'code' => 'GE'],
            ['name' => 'Armenia', 'code' => 'AM'],
            ['name' => 'Azerbaijan', 'code' => 'AZ'],
            ['name' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'Tajikistan', 'code' => 'TJ'],
            ['name' => 'Turkmenistan', 'code' => 'TM'],
            ['name' => 'Mongolia', 'code' => 'MN'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Bhutan', 'code' => 'BT'],
            ['name' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Maldives', 'code' => 'MV'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Iran', 'code' => 'IR'],
            ['name' => 'Iraq', 'code' => 'IQ'],
            ['name' => 'Syria', 'code' => 'SY'],
            ['name' => 'Yemen', 'code' => 'YE']
        ];

        $country = $this->faker->randomElement($countries);

        return [
            'name' => $country['name'],
            'code' => $country['code'],
        ];
    }
}